


#ifndef TMR0_CONFIG_H_
#define TMR0_CONFIG_H_


#define TMR0_PRELOAD_VALUE			224
#define TMR0_OVER_FLOW_COUNTER		1954
#define TMR0_OUT_COMPARE_VALUE		249
#define TMR0_OUT_COMPARE_COUNTER	1500

#endif /* TMR0_CONGIF_H_ */